server:
  port: 8080 #启动端口号
spring:
  application:
    name: reggie_take_out #指定应用名称，不配置的话默认使用工程名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 562552
  #配置redis
  redis:
    host: 192.168.1.203
    port: 6379
    password: YinHang1024..
    database: 2

  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间

mybatis:
  #设置type搜索包的路径
  type-aliases-package: com.dida.reggie.entity
  #配置mapper的扫描
  mapper-locations: classpath:com/dida/reggie/mapper/*.xml

#配置照片缓存地址
reggie:
  path: D:\\DidaProject/reggieCache/





#mybatis-plus:
#  configuration:
#    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID