server:
  port: 8080 #启动端口号
spring:
  application:
    name: reggie_take_out #指定应用名称，不配置的话默认使用工程名
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ENC(j06EEcYR+dTrxHbniTHzg4X+1wy3wAp2)
      password: ENC(INphkgudJn9zHwMQYq/LE0C1cKv0X7mB)
  #配置redis
  redis:
    host: ENC(Ff0Z3C1PWq2gyBNQMZC+hZL2Y/O7deE7vjt9mYIDlxI=)
    port: 6379
    password: ENC(Ff0Z3C1PWq2gyBNQMZC+hZL2Y/O7deE7vjt9mYIDlxI=)
    database: 2

  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间

mybatis:
  #设置type搜索包的路径
  type-aliases-package: com.dida.reggie.entity
  #配置mapper的扫描
  mapper-locations: classpath:com/dida/reggie/mapper/*.xml

#配置照片缓存地址
reggie:
  path: D:\\DidaProject/reggieCache/

jasypt:
  encryptor:
    password: aaaaa
    algorithm: PBEWithMD5AndDES





#mybatis-plus:
#  configuration:
#    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID